-- DO NOT EDIT THIS FILE AFTER IT IS PUSHED IT WILL DIVERGE THE DATABASE
-- IF YOU WANT TO EDIT THE YOU HAVE TO ADD A SEPARATE V2__add_something.sql file

USE jobdb;

-- Indexes are declared inline rather than as separate CREATE INDEX statements:
-- MySQL 8 has no CREATE INDEX IF NOT EXISTS, so keeping them inside the table
-- definition is what makes this whole migration safe to re-run.
CREATE TABLE IF NOT EXISTS jobs (
    id                  CHAR(36)      NOT NULL,
    -- The human-readable handle an Agent reads down the phone: JOB- and six
    -- characters. VARCHAR(20) rather than CHAR(10) leaves room for the prefix
    -- or the length to change without a column alteration.
    job_reference       VARCHAR(20)   NOT NULL,
    customer_id         CHAR(36)      NOT NULL,
    asset_id            CHAR(36)      NOT NULL,
    service_category    VARCHAR(20)   NOT NULL,
    problem_description VARCHAR(1000) NOT NULL,
    priority            VARCHAR(10)   NOT NULL,
    region              VARCHAR(20)   NOT NULL,
    -- Nullable because a job is raised before it is scheduled. Nothing in the
    -- creation path sets it, so every row starts NULL and a later story fills
    -- it in. A DATE, not a TIMESTAMP - the day work is booked for has no time
    -- of day.
    scheduled_date      DATE          NULL,
    -- The Agent who raised the job. NOT NULL with no default: an audit column
    -- that can be skipped is one that will be. Until authentication exists
    -- there is no real user id to write, so the service supplies the all-zero
    -- GUID as an explicit "not attributed" value rather than leaving the
    -- column to a default nobody would notice.
    created_by          CHAR(36)      NOT NULL,
    -- Every job starts CREATED. Left to the column's default rather than sent
    -- on the INSERT, so the starting status is stated in one place.
    status              VARCHAR(20)   NOT NULL DEFAULT 'CREATED',
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    -- The reference is generated at random, so this index is not decoration:
    -- it is what actually makes a collision impossible, and the service reacts
    -- to the 1062 it raises by generating a fresh reference and retrying.
    UNIQUE KEY uq_jobs_job_reference (job_reference),
    -- Listing the jobs raised for one customer.
    KEY idx_jobs_customer_id (customer_id),
    -- Listing the service history of one unit.
    KEY idx_jobs_asset_id (asset_id),
    -- Dispatch filters by region to find the technicians who cover it, so this
    -- is the index its assignment queries will run on.
    KEY idx_jobs_region (region),

    CONSTRAINT chk_jobs_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    CONSTRAINT chk_jobs_service_category CHECK (service_category IN ('INSTALLATION', 'REPAIR', 'MAINTENANCE', 'INSPECTION', 'WARRANTY_CLAIM')),
    CONSTRAINT chk_jobs_region CHECK (region IN ('WESTERN', 'CENTRAL', 'SOUTHERN', 'NORTHERN', 'EASTERN', 'NORTH_WESTERN', 'NORTH_CENTRAL', 'UVA', 'SABARAGAMUWA'))

    -- No foreign keys. customer_id and asset_id name rows in customerdb, which
    -- is a different database owned by a different service - MySQL cannot
    -- constrain across that boundary, and doing so would couple the two
    -- services' schemas. The reference is validated over HTTP before the insert
    -- instead.
);
