-- DO NOT EDIT THIS FILE AFTER IT IS PUSHED IT WILL DIVERGE THE DATABASE
-- IF YOU WANT TO EDIT THE YOU HAVE TO ADD A SEPARATE V3__add_something.sql file

-- ASSMS-29: assignment context absorbed from the Dispatch-owned JobAssigned
-- event.
--
-- Dispatch decides assignments and owns technician_assignments in dispatchdb.
-- None of these columns is ever written by an API request; they are a local copy
-- of a fact another service published, kept here so a job read back from the Job
-- Service shows who it went to without a cross-service call.
--
-- Every column is nullable, because a job is raised before it is assigned. There
-- is no default and no backfill: rows created before this migration ran were
-- genuinely never assigned, and writing a placeholder would invent an assignment
-- that did not happen.
--
-- assigned_at is TIMESTAMP(6), not a plain TIMESTAMP. The consumer compares the
-- incoming event's timestamp against the stored one to reject a stale or
-- redelivered assignment, and truncating to whole seconds would make two
-- assignments in the same second indistinguishable - collapsing exactly the
-- comparison that guard depends on.
--
-- MySQL 8 has no ADD COLUMN IF NOT EXISTS, so unlike the CREATE TABLE migrations
-- this file cannot be made re-runnable by syntax alone. Each statement is
-- therefore guarded against information_schema and prepared only when it is
-- actually needed, which keeps the same "safe to run twice" property the rest of
-- the migration set has.

SET @ddl := (
    SELECT IF(
        COUNT(*) = 0,
        'ALTER TABLE jobs
            ADD COLUMN assignment_id                  CHAR(36)     NULL,
            ADD COLUMN assigned_technician_id         CHAR(36)     NULL,
            ADD COLUMN assigned_technician_reference  VARCHAR(30)  NULL,
            ADD COLUMN assigned_at                    TIMESTAMP(6) NULL',
        'DO 0'
    )
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'jobs'
      AND COLUMN_NAME = 'assignment_id'
);

PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Listing the jobs one technician is carrying. Reporting answers this across all
-- jobs from its own projection, but the Job Service is asked it about a single
-- technician often enough that a full scan of jobs is the wrong answer.
SET @ddl := (
    SELECT IF(
        COUNT(*) = 0,
        'ALTER TABLE jobs ADD KEY idx_jobs_assigned_technician_id (assigned_technician_id)',
        'DO 0'
    )
    FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'jobs'
      AND INDEX_NAME = 'idx_jobs_assigned_technician_id'
);

PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Note on status: the jobs table deliberately carries no CHECK constraint on
-- status, so ASSIGNED needs no schema change to become a legal value. That was
-- already true before this migration; it is written down because the consumer
-- added alongside it is the first thing to write a status other than CREATED,
-- and the absence of a constraint is what makes that a one-line change rather
-- than a coordinated release.
--
-- No foreign key on assignment_id or assigned_technician_id: both name rows in
-- dispatchdb, a different database owned by a different service, which MySQL
-- cannot constrain across.
