-- DO NOT EDIT THIS FILE AFTER IT IS PUSHED IT WILL DIVERGE THE DATABASE
-- IF YOU WANT TO EDIT THIS YOU HAVE TO ADD A SEPARATE V4__add_something.sql file

-- ASSMS-36 US-10A: persist the moment a Technician starts an assigned job.
--
-- started_at is nullable because only jobs that have been moved to IN_PROGRESS
-- carry a value. Rows created before this migration and rows still in CREATED or
-- ASSIGNED have no start time, and writing a placeholder would invent a fact
-- that did not happen.
--
-- TIMESTAMP(6) matches assigned_at: sub-second precision is consistent across
-- all lifecycle timestamps, and a plain TIMESTAMP would truncate comparisons
-- that rely on microsecond ordering.
ALTER TABLE jobs
    ADD COLUMN started_at TIMESTAMP(6) NULL;
