-- DO NOT EDIT THIS FILE AFTER IT IS PUSHED IT WILL DIVERGE THE DATABASE
-- IF YOU WANT TO EDIT THIS YOU HAVE TO ADD A SEPARATE V5__add_something.sql file

-- ASSMS-37 US-11A: persist service work records added by the active Technician.

USE jobdb;

CREATE TABLE IF NOT EXISTS service_work_records (
    id                   CHAR(36)      NOT NULL,
    job_id               CHAR(36)      NOT NULL,
    job_reference        VARCHAR(20)   NOT NULL,
    technician_id        CHAR(36)      NOT NULL,
    technician_reference VARCHAR(30)   NOT NULL,
    content              VARCHAR(2000) NOT NULL,
    recorded_at          TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_at           TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    KEY idx_service_work_records_job_id (job_id),
    KEY idx_service_work_records_technician_id (technician_id),

    CONSTRAINT fk_service_work_records_job_id FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT
);
