-- DO NOT EDIT THIS FILE AFTER IT IS PUSHED IT WILL DIVERGE THE DATABASE
-- IF YOU WANT TO EDIT THIS YOU HAVE TO ADD A SEPARATE V6__add_something.sql file

-- ASSMS-85 US-10B: persist status history changes.

USE jobdb;

CREATE TABLE IF NOT EXISTS job_status_history (
    id              CHAR(36)      NOT NULL,
    job_id          CHAR(36)      NOT NULL,
    previous_status VARCHAR(20)   NULL,
    new_status      VARCHAR(20)   NOT NULL,
    actor_id        CHAR(36)      NOT NULL,
    created_at      TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (id),
    KEY idx_job_status_history_job_id (job_id),
    CONSTRAINT fk_job_status_history_job_id FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT
);
