-- DO NOT EDIT THIS FILE AFTER IT IS PUSHED IT WILL DIVERGE THE DATABASE
-- IF YOU WANT TO EDIT THIS YOU HAVE TO ADD A SEPARATE V7__add_something.sql file

-- ASSMS-89 US-11E: persist completed_at timestamp when a Technician completes an in-progress job.

USE jobdb;

ALTER TABLE jobs
    ADD COLUMN completed_at TIMESTAMP(6) NULL;
